services:
  postgres:
    image: "pgvector/pgvector:pg16"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - ./data/schema_py.sql:/docker-entrypoint-initdb.d/schema_py.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: smask_app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
volumes:
  pgdata:
