export type PatientPreset = {
    label: string;
    value: string;
    data: Record<string, any>;
};

// Symptoms phrased as a layperson; no explicit give-aways
export const patientPresets: PatientPreset[] = [
    {
        label: 'Sởi',
        value: 'measles',
        data: {
            full_name: 'Nguyễn Văn A',
            birthday: '1990-05-10',
            gender: 'Male',
            occupation: 'Công nhân',
            nationality: 'Việt Nam',
            address: '123 Đường Lạc Long Quân, Hà Nội',
        chief_complaint: 'Sốt, ho, nổi ban đỏ',
        medical_history:
            'Vài ngày nay sốt cao, ho khan, chảy mũi, mắt hơi cay, xuất hiện ban đỏ lan dần. Không rõ vì sao.',
            past_medical_history: 'Không bệnh mạn tính đã biết',
            current_medications: 'Không',
            allergies: 'Không ghi nhận',
            family_medical_history: 'Không có bệnh di truyền nổi bật',
            alcohol_consumption: 'never',
            alcohol_per_month_times: '',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: '',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'family',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: '',
            menstrual_cycle: '',
            recent_sexual_activity: null,
        },
    },
    {
        label: 'Dại',
        value: 'rabies',
        data: {
            full_name: 'Trần Văn B',
            birthday: '1988-08-20',
            gender: 'Male',
            occupation: 'Nhân viên giao hàng',
            nationality: 'Việt Nam',
            address: '45 Nguyễn Trãi, Hà Nội',
        chief_complaint: 'Sốt nhẹ, đau đầu, mỏi người',
        medical_history:
            'Vài ngày nay sốt nhẹ, đau đầu âm ỉ, người bứt rứt khó chịu. Tay chân hơi ê ẩm, không rõ nguyên nhân, chưa đi khám.',
            past_medical_history: 'Không bệnh mạn tính đã biết',
            current_medications: 'Không',
            allergies: 'Không ghi nhận',
            family_medical_history: 'Không rõ bệnh gia đình',
            alcohol_consumption: 'occasionally',
            alcohol_per_month_times: '1',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '330',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: 'Bia',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'family',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: '',
            menstrual_cycle: '',
            recent_sexual_activity: null,
        },
    },
    {
        label: 'COPD',
        value: 'copd',
        data: {
            full_name: 'Phạm Văn C',
            birthday: '1965-03-15',
            gender: 'Male',
            occupation: 'Thợ xây',
            nationality: 'Việt Nam',
            address: '12/5 Trần Hưng Đạo, Đà Nẵng',
        chief_complaint: 'Khó thở tăng dần, ho dai dẳng',
        medical_history:
            'Ho khan lâu ngày, gần đây dễ hụt hơi khi đi bộ nhanh, thỉnh thoảng cảm giác nặng ngực. Có hút thuốc lâu năm.',
            past_medical_history: 'Không rõ bệnh phổi trước đó',
            current_medications: 'Không uống thuốc đều',
            allergies: 'Chưa ghi nhận',
            family_medical_history: 'Không rõ bệnh phổi gia đình',
            alcohol_consumption: 'occasionally',
            alcohol_per_month_times: '2',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '500',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: 'Bia',
            smoking_habit: 'current',
            smoking_start_age: '20',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '10',
            living_situation: 'family',
            daily_activity_independence: 'partially',
            recent_travel_history: 'no',
            menstruation_status: '',
            menstrual_cycle: '',
            recent_sexual_activity: null,
        },
    },
    {
        label: 'Lao phổi',
        value: 'tb',
        data: {
            full_name: 'Đỗ Thị D',
            birthday: '1995-09-09',
            gender: 'Female',
            occupation: 'Nhân viên bán hàng',
            nationality: 'Việt Nam',
            address: '56 Hoàng Hoa Thám, Hà Nội',
        chief_complaint: 'Ho kéo dài, gầy sút cân',
        medical_history:
            'Ho khan nhiều tuần, đôi lúc khạc ít đàm, hay mệt, ăn kém, sút cân nhẹ. Thỉnh thoảng hơi sốt về chiều.',
            past_medical_history: 'Không bệnh mạn tính',
            current_medications: 'Không',
            allergies: 'Không',
            family_medical_history: 'Không rõ có người mắc lao',
            alcohol_consumption: 'never',
            alcohol_per_month_times: '',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: '',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'family',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: 'Đều',
            menstrual_cycle: '30 ngày',
            recent_sexual_activity: false,
        },
    },
    {
        label: 'Viêm dạ dày',
        value: 'gastritis',
        data: {
            full_name: 'Lê Thị E',
            birthday: '1985-12-01',
            gender: 'Female',
            occupation: 'Nhân viên văn phòng',
            nationality: 'Việt Nam',
            address: '22 Lý Tự Trọng, TP.HCM',
        chief_complaint: 'Đau âm ỉ vùng thượng vị',
        medical_history:
            'Đau âm ỉ trên rốn vài ngày, đầy hơi, buồn nôn nhẹ, ăn vào hay khó chịu. Hay ăn uống thất thường, áp lực công việc.',
            past_medical_history: 'Không loét dạ dày trước đây',
            current_medications: 'Thỉnh thoảng uống thuốc giảm đau',
            allergies: 'Không',
            family_medical_history: 'Không rõ tiền sử loét',
            alcohol_consumption: 'occasionally',
            alcohol_per_month_times: '1',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '150',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: 'Rượu vang',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'family',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: 'Đều',
            menstrual_cycle: '28-30 ngày',
            recent_sexual_activity: true,
        },
    },
    {
        label: 'Viêm tuyến tiền liệt',
        value: 'prostatitis',
        data: {
            full_name: 'Ngô Văn F',
            birthday: '1978-07-07',
            gender: 'Male',
            occupation: 'Kỹ sư',
            nationality: 'Việt Nam',
            address: '89 Pasteur, TP.HCM',
        chief_complaint: 'Tiểu khó, đau tức vùng dưới',
        medical_history:
            'Vài ngày nay tiểu hơi rát, tia tiểu yếu, cảm giác nặng tức vùng dưới. Hơi mệt, uể oải.',
            past_medical_history: 'Không bệnh mạn tính',
            current_medications: 'Không',
            allergies: 'Không',
            family_medical_history: 'Không rõ',
            alcohol_consumption: 'occasionally',
            alcohol_per_month_times: '2',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '330',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: 'Bia',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'family',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: '',
            menstrual_cycle: '',
            recent_sexual_activity: true,
        },
    },
    {
        label: 'Lậu / Chlamydia',
        value: 'sti',
        data: {
            full_name: 'Phan Thị G',
            birthday: '1998-11-30',
            gender: 'Female',
            occupation: 'Nhân viên kinh doanh',
            nationality: 'Việt Nam',
            address: '12 Nguyễn Huệ, TP.HCM',
        chief_complaint: 'Khó chịu vùng kín, tiểu rát',
        medical_history:
            'Vùng kín khó chịu, tiểu rát nhẹ, dịch âm đạo hơi khác vài ngày nay, lo lắng sau lần quan hệ gần đây.',
            past_medical_history: 'Không bệnh mạn tính',
            current_medications: 'Không',
            allergies: 'Không',
            family_medical_history: 'Không rõ',
            alcohol_consumption: 'never',
            alcohol_per_month_times: '',
            alcohol_per_week_times: '',
            alcohol_per_time_ml: '',
            alcohol_avg_per_day_ml: '',
            alcohol_drink_type: '',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'alone',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: 'Đều',
            menstrual_cycle: '30 ngày',
            recent_sexual_activity: true,
        },
    },
    {
        label: 'Rối loạn lipid máu',
        value: 'dyslipidemia',
        data: {
            full_name: 'Hoàng Văn H',
            birthday: '1972-04-18',
            gender: 'Male',
            occupation: 'Kế toán',
            nationality: 'Việt Nam',
            address: '5B Hai Bà Trưng, Hà Nội',
        chief_complaint: 'Mệt mỏi, phát hiện mỡ máu cao',
        medical_history:
            'Thỉnh thoảng mệt, nặng đầu, khám sức khỏe gần đây nói mỡ máu cao. Ít vận động, hay ăn đồ chiên xào.',
            past_medical_history: 'Tăng huyết áp nhẹ',
            current_medications: 'Thuốc huyết áp không đều',
            allergies: 'Không',
            family_medical_history: 'Cha từng đột quỵ',
            alcohol_consumption: 'frequently',
            alcohol_per_month_times: '',
            alcohol_per_week_times: '3',
            alcohol_per_time_ml: '',
            alcohol_avg_per_day_ml: '200',
            alcohol_drink_type: 'Bia/rượu',
            smoking_habit: 'used_to_quit',
            smoking_start_age: '20',
            smoking_end_age: '35',
            smoking_cigarettes_per_day: '5',
            living_situation: 'family',
            daily_activity_independence: 'yes',
            recent_travel_history: 'no',
            menstruation_status: '',
            menstrual_cycle: '',
            recent_sexual_activity: false,
        },
    },
    {
        label: 'Gout',
        value: 'gout',
        data: {
            full_name: 'Trịnh Văn K',
            birthday: '1982-01-22',
            gender: 'Male',
            occupation: 'Nhân viên kinh doanh',
            nationality: 'Việt Nam',
            address: '77 Nguyễn Văn Linh, Đà Nẵng',
        chief_complaint: 'Đau sưng khớp bàn chân',
        medical_history:
            'Khớp ngón chân cái sưng, đau về đêm, đi lại khó. Gần đây có ăn uống nhiều đạm, chưa đi kiểm tra.',
            past_medical_history: 'Không bệnh mạn tính đã biết',
            current_medications: 'Không',
            allergies: 'Không',
            family_medical_history: 'Không rõ',
            alcohol_consumption: 'frequently',
            alcohol_per_month_times: '',
            alcohol_per_week_times: '2',
            alcohol_per_time_ml: '',
            alcohol_avg_per_day_ml: '300',
            alcohol_drink_type: 'Bia',
            smoking_habit: 'never',
            smoking_start_age: '',
            smoking_end_age: '',
            smoking_cigarettes_per_day: '',
            living_situation: 'family',
            daily_activity_independence: 'partially',
            recent_travel_history: 'no',
            menstruation_status: '',
            menstrual_cycle: '',
            recent_sexual_activity: false,
        },
    },
];
