"""init chat_sessions table

Revision ID: 28a10d997686
Revises: 
Create Date: 2025-05-06 18:41:01.001990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a10d997686'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('medical_record', sa.JSON(), nullable=True),
    sa.Column('diagnosis_response', sa.JSON(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('follow_up_questions', sa.JSON(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
